<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>edf2e881-1c2f-4d4e-880f-fc56028a20fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bt-a-mybutton.bt-bg-black.button-cancel-book</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='payment-form']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b800ccd-5d06-4966-af78-dc5e14c0cf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bt-a-mybutton bt-bg-black button-cancel-book</value>
      <webElementGuid>d0d84806-4ac1-480e-bdb7-2f09335c26bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>707be355-9a41-4514-bb06-b283430e67f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;seat-sections-content&quot;]/div[@class=&quot;container big-step cart-breakdown&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;payment-form&quot;]/div[@class=&quot;col-md-12 choice-pay-ct&quot;]/form[@id=&quot;payment-form&quot;]/div[@class=&quot;one-liner&quot;]/a[@class=&quot;bt-a-mybutton bt-bg-black button-cancel-book&quot;]</value>
      <webElementGuid>765c513e-e806-48d6-ad23-999cbfd72738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div[2]/a</value>
      <webElementGuid>d68042d0-b503-4a2f-9d7f-468246ff7773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>58d5057c-7c03-4a69-b75a-54d7cdc90031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Information'])[1]/following::a[1]</value>
      <webElementGuid>a4654e29-8a3e-4404-9b31-5266eabab149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amex'])[1]/following::a[1]</value>
      <webElementGuid>df2d5bd5-688a-45dc-a8ea-06c3c423d898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shaw Theatres Lido'])[1]/preceding::a[1]</value>
      <webElementGuid>c1d44ca0-c50b-43ab-bd7f-fc10bcab8fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and conditions of use'])[1]/preceding::a[1]</value>
      <webElementGuid>bc225a77-d88f-4ca3-89b5-55dcc8e77334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>4a378af9-b838-4d9e-91c4-19293563784f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>f2129569-621c-4533-8cd6-eef1fcb49e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>f01776cb-9485-42bf-972a-92ac13bef417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
