<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Confirm_h_seat</name>
   <tag></tag>
   <elementGuidId>01ff4608-2ba5-4961-94da-9aac02a42d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmSeatSelection</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='confirmSeatSelection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f67a22f-e179-4664-a90c-dbe39bb020c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-red inline</value>
      <webElementGuid>081cebc9-d368-452e-9313-0c8b23c8a1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmSeatSelection</value>
      <webElementGuid>2646c986-1067-4868-94c5-4c7fe4d89f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#confirmSeat</value>
      <webElementGuid>001fea88-bb0b-40b1-afb8-9bd730d5057b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>b08bcc83-a9d7-4531-86be-d290e5d5fbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmSeatSelection&quot;)</value>
      <webElementGuid>7af403bd-206e-4fbb-8e5b-8e22d61fca2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='confirmSeatSelection']</value>
      <webElementGuid>d57167c5-e115-4c7b-a309-f8f2937f92ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-seat-confirmation']/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>9818b3c2-a4fa-42c4-9be3-e9b574fa6b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Confirm')]</value>
      <webElementGuid>12f116af-7f47-4a69-bbdf-3de853e2321d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Seat Selection'])[1]/following::a[2]</value>
      <webElementGuid>e142879a-c63d-4bba-a94c-d224eabf1b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/following::a[3]</value>
      <webElementGuid>79031b86-4e86-454c-a521-53181dee4187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seat Selection Invalid'])[1]/preceding::a[1]</value>
      <webElementGuid>91fac306-54db-4555-a863-e12ec5492118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::a[1]</value>
      <webElementGuid>85f4b1de-043d-4e9e-b593-e45faef44545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>5f2ea4fe-dcd2-4159-95cd-3ffff00716fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#confirmSeat')]</value>
      <webElementGuid>9a229155-8971-4110-a4ce-b5e834b42407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>d37a4208-3d7e-465e-8192-1fb489ba40fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'confirmSeatSelection' and @href = '#confirmSeat' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>d82af50a-bf86-4eb7-9f67-7aea1cd28d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
