<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Proceed</name>
   <tag></tag>
   <elementGuidId>a8cf7ca6-c356-47fe-8de8-49dae5e7d7d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.form-control.mid-wide.bg-white.inline.seat-warn-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='different-row-of-seats']/div[2]/div/div/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96abb501-7a9b-435a-be7b-dcc6455f99c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-white inline seat-warn-btn</value>
      <webElementGuid>0c0c0823-17f7-44dd-87ff-5216ff3fa3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#confirmSeat</value>
      <webElementGuid>cce051df-25c0-46a9-b4d5-28f0664191d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>3dc96e8a-acca-40ee-81fe-f8788545613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;different-row-of-seats&quot;)/div[@class=&quot;popup-float-wrapper pad mainwidth&quot;]/div[@class=&quot;popup-wrapper&quot;]/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;popup-control&quot;]/a[@class=&quot;button form-control mid-wide bg-white inline seat-warn-btn&quot;]</value>
      <webElementGuid>fd82823f-3f39-4ba5-9c90-4991cc6663cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='different-row-of-seats']/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>0f31d512-2e03-40d2-a992-bde86cc0d25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Proceed')]</value>
      <webElementGuid>7d5a7bba-14f7-446e-ad4b-a981a077d51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row: B1'])[1]/following::a[2]</value>
      <webElementGuid>1b54cc65-aeab-4940-9700-5dcbe80f6591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row: HH2 |'])[1]/following::a[2]</value>
      <webElementGuid>f5036ec9-7b9e-4b63-872a-28e506ae0efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[2]/preceding::a[2]</value>
      <webElementGuid>7b76a7d0-574f-403a-8f1b-4216ae4d7cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agree'])[2]/preceding::a[2]</value>
      <webElementGuid>4a6edc27-403c-456e-9ea8-f781d2312c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed']/parent::*</value>
      <webElementGuid>105cb32e-1d71-4bd6-9c45-a35e179aabf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#confirmSeat')])[2]</value>
      <webElementGuid>6ed9e9cc-6d83-4ddb-a9bb-dffe4fbbfa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[10]/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>0ca24816-57b6-4941-8c77-a3a225f1db8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#confirmSeat' and (text() = 'Proceed' or . = 'Proceed')]</value>
      <webElementGuid>0b382686-25af-45a8-a7f1-82485c12723c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
