<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose your payment method_gender</name>
   <tag></tag>
   <elementGuidId>effd2625-ad4c-40cd-97e3-70ab0133dfdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal-payment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal-payment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a654d967-20ac-4798-86b0-96242ec20994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a2d61c0c-8b13-470b-9512-29c8918be17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal-payment</value>
      <webElementGuid>f6c076cd-2b25-4552-b1a2-cd2d4aa41a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>82fc4e99-9b7c-4ba3-a2be-4519d6d3a094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>0518e353-a069-4c4b-ae9c-ef63092b935c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal-payment&quot;)</value>
      <webElementGuid>71910c78-eb6d-48cb-b630-c7b03d8e6001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal-payment']</value>
      <webElementGuid>7b9a16a2-ee8f-4521-91e0-21131f09e355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-payment-method']/input</value>
      <webElementGuid>378bb789-7941-4754-8c90-1bff129ec2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>9b4a3f8f-5bdc-4aa8-82a7-ecad6e025442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'normal-payment' and @name = 'gender']</value>
      <webElementGuid>edb95d55-bb1b-498a-bb2d-a5f2cd7326f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
