<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agree</name>
   <tag></tag>
   <elementGuidId>0bc90df7-b564-4227-806e-71c4dd383e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='rating_confirm'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup-rating-warning > div.popup-float-wrapper.popup-alert > div.popup-wrapper > div.popup-inner > div.popup-control > #rating_confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ee7f2d1-e153-42fd-ae54-99a534b3644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-red inline</value>
      <webElementGuid>07006fda-05af-4224-a209-27f215fabd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rating_confirm</value>
      <webElementGuid>432fbc19-cae5-4ab0-8401-178041658fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agree</value>
      <webElementGuid>0cca3c5c-dcc9-4d71-b70a-72eaabbd9d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-rating-warning&quot;)/div[@class=&quot;popup-float-wrapper popup-alert&quot;]/div[@class=&quot;popup-wrapper&quot;]/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;popup-control&quot;]/a[@id=&quot;rating_confirm&quot;]</value>
      <webElementGuid>479308b4-e314-4858-958d-3645095788dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='rating_confirm'])[2]</value>
      <webElementGuid>3a8362fc-359d-44b3-a2e1-dcdee122278e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-rating-warning']/div[2]/div/div/div[3]/a</value>
      <webElementGuid>85d668c1-e87f-498e-974c-160b4a20bb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agree')]</value>
      <webElementGuid>b7cb310e-d165-4f75-9016-2deff93779d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please note that this film is rated M18 - Mature 18 for persons 18 years and above'])[1]/following::a[1]</value>
      <webElementGuid>840637a6-cb4c-4f65-8324-2bb1d61abd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[1]/following::a[1]</value>
      <webElementGuid>a0f1b3f9-ced4-42bb-829c-4541bda53070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/preceding::a[1]</value>
      <webElementGuid>a41a9156-6b11-40c3-a7cd-74f4f4403e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different Rows of Seats'])[1]/preceding::a[3]</value>
      <webElementGuid>f483ff64-919a-43cb-8772-aa0e9c91f367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agree']/parent::*</value>
      <webElementGuid>1419f595-1427-444b-a3ee-503d7fa51ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div[2]/div/div/div[3]/a</value>
      <webElementGuid>997e41e2-ed82-48e5-b44f-6362f576d65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rating_confirm' and (text() = 'Agree' or . = 'Agree')]</value>
      <webElementGuid>b7f499cc-eec4-4fea-a407-dc91eb71d0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
