<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTINUE</name>
   <tag></tag>
   <elementGuidId>e5a27e69-762f-42e4-8811-a59952a9f364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotion']/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-custom.text-uppercase.btn-checkout.mar-top-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87d5c353-9315-4b1f-bb7b-556f902536c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-custom text-uppercase btn-checkout mar-top-1</value>
      <webElementGuid>5f16f805-9b22-4090-9720-cd97c4bcda1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUE</value>
      <webElementGuid>805f5347-34fa-4ea0-97e0-68304067c04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotion&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-right col-lg-7 col-lg-push-5 col-xs-12 col-sm-8 col-sm-push-4 clearfix func-btn&quot;]/div[@class=&quot;clearfix&quot;]/a[@class=&quot;btn btn-primary btn-custom text-uppercase btn-checkout mar-top-1&quot;]</value>
      <webElementGuid>4088d36e-eb33-496d-9fb4-7891b7965c67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotion']/div[2]/div/div/a</value>
      <webElementGuid>f5d9fcaa-c5da-40f6-bff6-1250cda9800f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CONTINUE')]</value>
      <webElementGuid>fd2d078a-33af-4dbf-9ccd-3e62faa6e110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/following::a[1]</value>
      <webElementGuid>6fec87a0-7106-45b4-b3af-ac8467f249d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[1]/preceding::a[2]</value>
      <webElementGuid>91ed31a5-b73f-4b58-ba88-54be44ccee59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agree'])[1]/preceding::a[2]</value>
      <webElementGuid>5c6aad0f-95ab-4d52-93ad-f4b96bfb6598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUE']/parent::*</value>
      <webElementGuid>559bd097-5449-4d8f-92e8-889ae0451bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>27f5c8c5-0f5a-4991-acb2-4525ac29bb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'CONTINUE' or . = 'CONTINUE')]</value>
      <webElementGuid>8157fd2d-7389-4003-bfc7-924cde58d99b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
