<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_0300 PM</name>
   <tag></tag>
   <elementGuidId>f001281b-8ca1-43d4-93be-3463b19ea994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movieData']/div[4]/div/div/div/div[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c226c7f0-97ef-45c7-966f-dc99e74f9ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell cell-note </value>
      <webElementGuid>18c523ea-90d7-49b2-adb2-d46cf0957580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-balloon-pos</name>
      <type>Main</type>
      <value>down</value>
      <webElementGuid>c0b02859-4397-48b8-95af-86195e23e224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-balloon</name>
      <type>Main</type>
      <value>Lido Hall 3
 27 Mar 2023</value>
      <webElementGuid>eb847600-8c0e-49b0-bc7c-3209c5c8310a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/seat-selection/20662</value>
      <webElementGuid>8ccff245-819f-4d3d-abab-104e8004dc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>03:00 PM*</value>
      <webElementGuid>62effecf-08b1-4bca-b5b9-b619b34db581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movieData&quot;)/div[4]/div[@class=&quot;location-area-persist&quot;]/div[1]/div[@class=&quot;movie_item-movie row block-list-showtimes&quot;]/div[@class=&quot;col-lg-8 col-sm-7&quot;]/div[@class=&quot;showtimes-block&quot;]/a[@class=&quot;cell cell-note&quot;]</value>
      <webElementGuid>bbd71745-b89a-460b-b882-5c91370ea6de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movieData']/div[4]/div/div/div/div[4]/div/a</value>
      <webElementGuid>f91ba4eb-ded3-49b8-8fc5-965d3a6e039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shaw Theatres Lido'])[1]/following::a[1]</value>
      <webElementGuid>a1408cff-2bc3-41ea-abc7-f25aed3ff98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timing'])[1]/following::a[1]</value>
      <webElementGuid>fe8478a1-c8d3-4b38-a444-bc570d831e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::a[1]</value>
      <webElementGuid>b3ca97b8-084e-467b-93f6-6067c05b9161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='03:00 PM']/parent::*</value>
      <webElementGuid>3d702806-5489-420c-853e-a91fd77ccb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/seat-selection/20662')]</value>
      <webElementGuid>ae386a82-1c9b-4a1e-b964-601f83b5127c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>8c6d2ff8-066b-4d88-982f-2b4e9990e529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/seat-selection/20662' and (text() = '03:00 PM*' or . = '03:00 PM*')]</value>
      <webElementGuid>5f362020-12ee-4c0d-a43f-8c8e7aa77982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
