<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f8b53a44-085d-4d02-83f3-f27866e81d29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[9]/div/div/div/div[3]/div/div/div[3]/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ef9ae4d-392a-44f2-badb-81ff116cde11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://snow-shaw-cdn.azureedge.net/prd/content/images/movie/default/en-sg/144-Poster-1678935885709</value>
      <webElementGuid>f6a61393-29f9-4f84-8dfc-bbb17039f1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;movies-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;container block-list-movies&quot;]/div[@class=&quot;row movie-list&quot;]/div[@class=&quot;col-lg-11&quot;]/div[@class=&quot;row movie-lists&quot;]/div[@class=&quot;movies_item-movie row block-list-showtimes&quot;]/div[@class=&quot;movie_list_poster&quot;]/div[@class=&quot;movies_ct-item clearfix&quot;]/a[@class=&quot;block-img p-t-0&quot;]/img[1]</value>
      <webElementGuid>e036f8f6-74ae-4d20-bba5-721a1fee0c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[9]/div/div/div/div[3]/div/div/div[3]/div/div/div/a/img</value>
      <webElementGuid>37441f86-7979-472d-8813-ac1475418e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://snow-shaw-cdn.azureedge.net/prd/content/images/movie/default/en-sg/144-Poster-1678935885709')]</value>
      <webElementGuid>a47b2cd0-a2e4-4250-91e1-f5b54311941d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>73576673-3ef9-40c5-8ef8-345968274ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://snow-shaw-cdn.azureedge.net/prd/content/images/movie/default/en-sg/144-Poster-1678935885709']</value>
      <webElementGuid>83f0e7f8-af05-45ce-a07a-e9059e65212b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
